# Generated by Django 4.0.3 on 2022-03-31 12:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_desciption_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='big_description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), null=True, size=20),
        ),
    ]
