# Generated by Django 4.0.3 on 2022-04-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_big_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category.jps', upload_to='', verbose_name='Rasmi'),
            preserve_default=False,
        ),
    ]
