# Generated by Django 4.0.3 on 2022-04-01 06:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='big_description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), null=True, size=100),
        ),
    ]
