# Generated by Django 4.0.3 on 2022-04-01 10:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_big_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='big_description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=355), null=True, size=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=355, verbose_name='Qisqacha'),
        ),
    ]
