# Generated by Django 3.1.2 on 2022-04-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220402_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=100, verbose_name='Rasmi'),
        ),
    ]
