# Generated by Django 4.0.3 on 2022-04-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220405_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='header_image',
            field=models.CharField(default='image', max_length=100, verbose_name='Karusel rasmi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
