# Generated by Django 4.0.3 on 2022-04-13 09:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=15), default='{arrays}', size=8, verbose_name='Qisqacha'),
            preserve_default=False,
        ),
    ]
