# Generated by Django 4.0.3 on 2022-04-13 10:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description_key',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), default='{Угловая точность}', size=15, verbose_name='Qisqacha nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), default='{2}', size=15, verbose_name='Qisqacha qiymati'),
            preserve_default=False,
        ),
    ]
